system: include('environment', required=False)
users: list(include('id_map', required=True), required=True)
---
environment:
    log_verbosity: str(required=False)
    config_backup_enabled: str(required=False)
    workspace_user: str(required=False)
    workspace_group: str(required=False)
    workspace_user_password: str(required=False)
    workspace_user_shell: str(required=False)
    resources_path: str(required=False)
    workspace_home: str(required=False)
    apps_path: str(required=False)
    data_path: str(required=False)
    proxy_base_url: str(required=False)
    zsh_prompt: str(required=False)
    zsh_theme: str(required=False)
    zsh_plugins: str(required=False)
    conda_env_path: str(required=False)
    caddy_virtual_port: str(required=False)
    caddy_virtual_host: str(required=False)
    caddy_virtual_bind_net: str(required=False)
    caddy_virtual_proto: str(required=False)
    caddy_virtual_base_url: str(required=False)
    caddy_proxy_encodings_gzip: str(required=False)
    caddy_proxy_encodings_zstd: str(required=False)
    caddy_proxy_templates: str(required=False)
    caddy_letsencrypt_email: str(required=False)
    caddy_letsencrypt_endpoint: str(required=False)
    caddy_http_port: str(required=False)
    caddy_https_enable: str(required=False)
    caddy_https_port: str(required=False)
    caddy_auto_https: str(required=False)
    caddy_workspace_ssl_enabled: str(required=False)
    fb_port: str(required=False)
    fb_base_url: str(required=False)
    fb_root_dir: str(required=False)
    vscode_bind_addr: str(required=False)
    vscode_base_url: str(required=False)
    app_bind_addr: str(required=False)
    app_base_url: str(required=False)
    app_root_dir: str(required=False)
    app_user: str(required=False)
    app_password: str(required=False)

---
id_map: include('user_map', required=True)
user_map:
    name: str(required=True)
    group: str(required=False)
    uid: str(required=True)
    gid: str(required=False)
    shell: str(required=False)
    password: str(required=False)
    directories: list(include('dir_map', required=False), required=False)
    backup_paths: list(str(required=False), required=False)
    conda: include('conda_map', required=False)
    zsh: include('zsh_map', required=False)
    ssh: include('ssh_map', required=False)
    filebrowser: include('filebrowser_map', required=False)
    vscode: include('vscode_map', required=False)
    apps: list(include('app_map', required=False), required=False)
dir_map:
    name: str(required=False)
    path: str(required=False)
    mode: str(required=False)
conda_map:
    env: str(required=False)
zsh_map:
    set_prompt: str(required=False)
    set_theme: str(required=False)
    set_plugins: str(required=False)
    prompt: list(str(required=False), required=False)
    theme: list(str(required=False), required=False)
    plugins: list(str(required=False), required=False)
ssh_map:
    authorized_keys: list(str(required=False), required=False)
    key_names: list(str(required=False), required=False)
    configs: list(include('ssh_config_map', required=False), required=False)
ssh_config_map:
    name: str(required=False)
    hostname: str(required=False)
    port: str(required=False)
    user: str(required=False)
    pub_key_auth: str(required=False)
    id_only: str(required=False)
    id_file_path: str(required=False)
filebrowser_map:
    port: str(required=True)
    base_url: str(required=False)
    root_dir: str(required=False)
vscode_map:
    bind_addr: str(required=True)
    base_url: str(required=False)
    extensions: list(str(required=False), required=False)
app_map:
    name: str(required=False)
    bind_addr: str(required=False)
    base_url: str(required=False)
    root_dir: str(required=False)
    user: str(required=False)
    password: str(required=False)


