version: "0.1"

info:
    name: "proneer/magento-dev-server"
    tags:
      - "v0.1"
      - "latest"
    maintainer: "Phillip Strefling"
    email: "phillip@proneer.co"
    organization: "Proneer Corp."
    version: "0.1"
    repository: "registry.dev.proneer.co"
    #build_dir: "../magento"
build:
    base: "ubuntu:20.04"
    entrypoint: "python3 /docker-entrypoint.py"
    projects:
      - directory: "base-cpu"
        dockerfiles:
          - file: "Dockerfile.base"
            repository: "registry.dev.proneer.co"
            name: "base"
            tag: "ubuntu20.04"
            from: "ubuntu:20.04"
      - directory: "dev-server"
        dockerfiles:
          - file: "Dockerfile.dev"
            repository: "registry.dev.proneer.co"
            name: "dev"
            tag: "ubuntu20.04"
            from: "registry.dev.proneer.co/base:ubuntu20.04"
      - directory: "lamp"
        dockerfiles:
          - file: "Dockerfile.base"
            repository: "registry.dev.proneer.co"
            name: "lamp"
            tag: "ubuntu20.04"
            from: "registry.dev.proneer.co/dev:ubuntu20.04"
      - directory: "magento-demo"
        dockerfiles:
          - file: "Dockerfile.base"
            repository: "registry.dev.proneer.co"
            name: "magento"
            tag: "base-ubuntu20.04"
            from: "registry.dev.proneer.co/lamp:ubuntu20.04"
          - file: "Dockerfile.tools"
            repository: "registry.dev.proneer.co"
            name: "magento"
            tag: "tools-ubuntu20.04"
            from: "registry.dev.proneer.co/magento:base-ubuntu20.04"
      - directory: "dev-server"
        dockerfiles:
          - file: "Dockerfile.vscode"
            repository: "registry.dev.proneer.co"
            name: "magento"
            tag: "webdev-ubuntu20.04"
            push_version: "v0.1"
            from: "registry.dev.proneer.co/magento:tools-ubuntu20.04"
