FROM registry.dev.proneer.co/cuda:10.1-cudnn7-devel-ubuntu18.04
MAINTAINER proneer <phillip@proneer.co>

######## Openpose Ubuntu 18.04 Dev ###########

### Image and project labels
LABEL \
    maintainer="proneer <phillip@proneer.co>" \
        org.label-schema.docker.dockerfile="/Dockerfile.bionic.dev" \
        org.label-schema.name="Openpose Ubuntu 18.04 Development Image" \
        org.label-schema.url="https://www.proneer.co"

### Technical Environment Variables
ENV \
    USER_GID=0 \
    DEBIAN_FRONTEND=noninteractive \
    RESOURCES_PATH="/resources"

### Install 
RUN \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        python3-numpy \
        python3-numpy \
    # Cleanup
    && clean-layer.sh \
    && rm -rf /var/lib/apt/lists/*

### Load OpenCV
WORKDIR $RESOURCES_PATH/openpose-docker
ENV \
    OPENCV_VERSION="4.2.0"
RUN \
    echo "**** building and installing opencv $OPENCV_VERSION ****" \
    && apt-get update \
    && apt-get purge -y \
        libopencv-dev \
    # Clean build directories
    && rm -rf opencv/build \
    && rm -rf opencv_contrib/build \
    # Create directory for installation
    && mkdir installation \
    && mkdir installation/OpenCV-"$OPENCV_VERSION" \
    && ln -s -f ../libv4l1-videodev.h videodev.h \
    && git clone --depth 1 --branch $OPENCV_VERSION https://github.com/opencv/opencv.git ./opencv \
    && git clone --depth 1 --branch $OPENCV_VERSION https://github.com/opencv/opencv_contrib.git ./opencv_contrib

### Build and Install OpenCV
WORKDIR $RESOURCES_PATH/openpose-docker/opencv/build
RUN \
    cmake \
        -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D PYTHON_DEFAULT_EXECUTABLE=$(which python) \
        -D INSTALL_C_EXAMPLES=ON \
        -D INSTALL_PYTHON_EXAMPLES=ON \
        -D WITH_TBB=ON \
        -D WITH_V4L=ON \
        -D WITH_CUDA=ON \
        -D WITH_CUDNN=ON \
        -D OPENCV_DNN_CUDA=ON \
        -D CUDA_ARCH_BIN=7.5 \
        -D ENABLE_FAST_MATH=1 \
        -D CUDA_FAST_MATH=1 \
        -D WITH_CUBLAS=1 \
        -D INSTALL_PYTHON_EXAMPLES=ON \
        -D WITH_V4L=ON \
        -D WITH_GTK=ON \
        -D OPENCV_GENERATE_PKGCONFIG=ON \
        -D OPENCV_PC_FILE_NAME=opencv.pc \
        -D OPENCV_ENABLE_NONFREE=ON \
        -D WITH_GSTREAMER=ON \
        -D WITH_QT=OFF \
        -D WITH_OPENGL=ON \
        -D ENABLE_CXX11=ON \
        #-D PYTHON3_NUMPY_INCLUDE_DIRS=/usr/lib/python/dist-packages/numpy \
        #-D OPENCV_PYTHON3_INSTALL_PATH=/usr/local/lib/python.6/dist-packages \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
        -D BUILD_EXAMPLES=ON \
        .. \
    && make -j$(nproc) && make install

### Load OpenPose
WORKDIR $RESOURCES_PATH/openpose-docker
ENV \
    OPENPOSE_VERSION="v1.6.0"
RUN \
    echo "**** building and installing openpose $OPENPOSE_VERSION ****" \
    && git clone --depth 1 --branch $OPENPOSE_VERSION https://github.com/CMU-Perceptual-Computing-Lab/openpose.git ./openpose \
    && cd ./openpose \
    && git submodule update --init --recursive --remote \
    # Clean build directories
    && rm -rf build

#WORKDIR $RESOURCES_PATH/openpose-docker
#RUN \
#    OPENPOSE_VERSION="v1.6.0" \
#    && echo "**** installing openpose $OPENPOSE_VERSION ****" \
#    && wget --no-verbose https://github.com/CMU-Perceptual-Computing-Lab/openpose/archive/$OPENPOSE_VERSION.tar.gz  -O ./openpose.tar.gz \
#    && tar xfz ./openpose.tar.gz && mv ./openpose-$OPENPOSE_VERSION/ ./openpose \
#    && rm ./openpose.tar.gz

### Build and install Openpose
WORKDIR $RESOURCES_PATH/openpose-docker/openpose/build  
RUN \
    cmake \
        -D BUILD_PYTHON=ON \
        -D USE_CUDNN=ON \
        -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
        -D DOWNLOAD_BODY_MPI_MODEL=ON \
        -D DOWNLOAD_BODY_COCO_MODE=ON \
        .. \
    && make -j `nproc`
#    && ln -s $RESOURCES_PATH/openpose-docker/openpose/bin? /usr/bin/