FROM registry.dev.proneer.co/dev-gpu:latest
MAINTAINER proneer <phillip@proneer.co>

######## VSCODE ###########

### Image and project labels
LABEL \
    maintainer="proneer <phillip@proneer.co>" \
        org.label-schema.docker.dockerfile="/Dockerfile.vscode" \
        org.label-schema.name="Development image loaded with Vscode, filebrowsers and various WebUI utilities" \
        org.label-schema.url="https://www.proneer.co"

USER root

### Technical Environment Variables
ENV \
    DEBIAN_FRONTEND=noninteractive \
    RESOURCES_PATH="/resources" \
    SCRIPTS_PATH="/scripts" \
    APPS_PATH="/apps" \
    DATA_PATH="/data" \
    WORKSPACE_HOME="/workspace"

### Install VScode server
RUN \
    curl -fsSL https://code-server.dev/install.sh | bash \
    # Cleanup
    && clean-layer.sh

### Install Filebrowser
RUN \
    curl -fsSL https://filebrowser.org/get.sh | bash \
    # Cleanup
    && clean-layer.sh

### Fix logging
RUN sed -i '/imklog/s/^/#/' /etc/rsyslog.conf

### Copy some configuration files
# copy system scripts
COPY scripts/__init__.py $SCRIPTS_PATH
COPY scripts/docker-entrypoint.py /
COPY scripts/functions.py $SCRIPTS_PATH
COPY scripts/run_workspace.py $SCRIPTS_PATH
COPY scripts/setup_ssh.py $SCRIPTS_PATH
COPY scripts/configure_user.py $SCRIPTS_PATH
COPY scripts/configure_cron.py $SCRIPTS_PATH
COPY scripts/backup_restore_config.py $SCRIPTS_PATH
# copy supervisor configs
COPY configs/supervisor/conf.d /etc/supervisor/conf.d/
COPY configs/supervisor/supervisord.conf /etc/supervisor/supervisord.conf
# copy custom libraries
COPY scripts/conda_parser.py $SCRIPTS_PATH
COPY scripts/users_mod.py $SCRIPTS_PATH
# copy user scripts
COPY scripts/configure_ssh.py $SCRIPTS_PATH
COPY scripts/configure_zsh.py $SCRIPTS_PATH
COPY scripts/configure_vscode.py $SCRIPTS_PATH
COPY scripts/configure_filebrowser.py $SCRIPTS_PATH
COPY scripts/configure_caddy.py $SCRIPTS_PATH
COPY scripts/configure_app.py $SCRIPTS_PATH
COPY scripts/setup_conda_envs.py $SCRIPTS_PATH
COPY scripts/run_installers.py $SCRIPTS_PATH
# copy main config file
#COPY scripts/config.yaml $SCRIPTS_PATH
# copy yaml validator schema
COPY scripts/schema.yaml $SCRIPTS_PATH

ENTRYPOINT ["python", "/docker-entrypoint.py"]