version: "3.8"

networks:
  proxy:

services:
  proneer-proxy:
    image: registry.dev.proneer.co/caddy-proxy:latest
    container_name: caddy-proxy
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      DATA_PATH: "/data"
      SSL_ISSUER: "internal"
      LETSENCRYPT_EMAIL: "admin@proneer.co"
      LETSENCRYPT_ENDPOINT: "dev"
      HTTP_PORT: "80"
      AUTO_HTTPS: "true"
      HTTPS_PORT: "443"

  pod1-pods1-gpu1:
    image: registry.dev.proneer.co/webdev:11.6.2-cudnn8-devel-ubuntu20.04-latest
    container_name: pod1_pods1_gpu1
    restart: unless-stopped
    runtime: nvidia
    entrypoint: "sudo python3 /docker-entrypoint.py"
    ports:
      - "2222:22"
    networks:
      - proxy
    volumes:
     - "/mnt/data/pods/pod1/envs:/opt/conda/envs"
     - "/mnt/data/pods/pod1/workspace:/workspace"
     - "/mnt/data/pods/pod1/home:/home"
     - "/mnt/data/pods/pod1/data:/data"
    deploy:
      resources:
        reservations:
          devices:
          - 'driver': 'nvidia'
            'count': 1
            'capabilities': ['gpu', 'utility']
    environment:
      LOG_VERBOSITY: "DEBUG"
      VIRTUAL_HOST: "pod1.pods1-gpu1.dev.proneer.co"
      # VIRTUAL_BIND_IP: "10.95.46.219"
      # VIRTUAL_BIND_NET: "proxy"
      # VIRTUAL_PORT: "8300"
      VIRTUAL_PORT: "80"
      VIRTUAL_PROTO: "http"
      # VIRTUAL_BASE_URL: "/"
      PROXY_ENCODINGS_GZIP: "true"
      PROXY_ENCODINGS_ZSTD: "true"
      PROXY_TEMPLATES: "true"
      # WORKSPACE_SSL_ENABLED: "false"
      # WORKSPACE_AUTH_USER: "test"
      # WORKSPACE_AUTH_PASSWORD: "${POD2_AUTH_PASSWORD:-password}"
      # FB_BASE_URL: "/data"
      # FB_PORT: "8055"
      # WORKSPACE_PORT: "8080"
      # VSCODE_BIND_ADDR: "0.0.0.0:8300"
      # VSCODE_BASE_URL: "/code"
      # CONDA_ENV_PATH: "/data/environment.yml"
      APP_BIND_ADDR': "0.0.0.0:3000"
      APP_BASE_URL': "/app"
      APP_ROOT_DIR': "/apps/app"
      # APP_USER': "admin"
      # APP_PASSWORD': "password"
      CONFIG_BACKUP_ENABLED: "true"
      # SHARED_LINKS_ENABLED: "true"
      # MAX_NUM_THREADS: "auto"
      NVIDIA_VISIBLE_DEVICES: "all"
