FROM registry.dev.proneer.co/base-gpu:latest
MAINTAINER proneer <phillip@proneer.co>

######## DEV ###########

### Image and project labels
LABEL \
    maintainer="proneer <phillip@proneer.co>" \
        org.label-schema.docker.dockerfile="/Dockerfile.dev" \
        org.label-schema.name="Base development image" \
        org.label-schema.url="https://www.proneer.co"

USER root

### Technical Environment Variables
ENV \
    USER_GID=0 \
    NB_USER="root" \
    DEBIAN_FRONTEND=noninteractive \
    RESOURCES_PATH="/resources" \
    SCRIPTS_PATH="/scripts" \
    CONFIGS_PATH="/configs" \
    APPS_PATH="/apps" \
    DATA_PATH="/data"

### Create install and data directories
RUN \
    mkdir $RESOURCES_PATH && chmod a+rwx $RESOURCES_PATH \
    && mkdir $SCRIPTS_PATH && chmod a+rwx $SCRIPTS_PATH \
    && mkdir $CONFIGS_PATH && chmod a+rwx $CONFIGS_PATH \
    && mkdir $APPS_PATH && chmod a+rwx $APPS_PATH \
    && mkdir $DATA_PATH && chmod a+rw $DATA_PATH

### Install python packages
RUN \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        python3-pip \
        python3-venv \
        python3-dev \
        python3-setuptools \
        python3-testresources \
    # Cleanup
    && clean-layer.sh \
    && rm -rf /var/lib/apt/lists/* \
    # Fix permissions
    && fix-permissions.sh $HOME

### tzdata Dependencies
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ="Etc/UTC"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

### Install extra packages
RUN \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        tzdata \
        jq \
        libssl-dev \
        libgdbm-dev \
        libncurses5-dev \
        libncursesw5-dev \
        # Shells
        csh \
        zsh \
        fish \
        # Editors
        nano \
        emacs \
        vim \
        # System tools
        tuptime \
        ncdu \
        iotop \
        psmisc \
        lsof \
        # Terminal tools
        htop \
        screen \
        tmate \
        tmux \
        less \
        rename \
        whereami \
        xclip \
        clinfo \
        xmlstarlet \
        parallel \
        yara \
        rpl \
        locate \
        bash-completion \
        expect \
        catimg \
        autojump \
        lynx \
        # Net tools
        net-tools \
        dnsutils \
        iputils-ping \
        iputils-tracepath \
        netcat \
        rsync \
        nmap \
        iftop \
        # Cuda tools
        nvtop \
        # Build libs
        build-essential \
        checkinstall \
        make \
        #cmake \
        cmake-curses-gui \
        pkg-config \
        yasm \
        swig \
        libicu-dev \
        # Net libs
        libsodium-dev \
        # Sec libs
        libargon2-0-dev \
        # Version control
        subversion \
        jed \
        git-flow \
        git-extras \
        # Visualization
        graphviz \
        # DB libs
        sqlite3 \
        libhiredis-dev \
        libpq-dev \
        libsqlite3-dev \
        unixodbc unixodbc-dev \
        libmariadb-dev \
        libmariadbclient-dev \
        #libmysqlclient-dev \
        # Required by Pyenv
        libreadline-dev \
        libedit-dev \
        xz-utils \
        gawk \
        # Image/Media support
        imagemagick \
        libtiff-dev \
        libjpeg8-dev \
        libjpeg-dev \
        libpng-dev \
        libglib2.0-0 \
        libxext6 \
        libsm6 \
        libxext-dev \
        libxrender1 \
        libzmq3-dev \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libdc1394-22-dev \
        libxine2-dev \
        libv4l-dev \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libfaac-dev \
        libmp3lame-dev \
        libtheora-dev \
        libvorbis-dev \
        libxvidcore-dev \
        libopencore-amrnb-dev \
        libopencore-amrwb-dev \
        libavresample-dev \
        x264 \
        v4l-utils \
        libgphoto2-dev \
        # GUI libs
        libgtk2.0-dev \
        # Protobuffer support
        protobuf-compiler \
        libprotobuf-dev \
        libprotoc-dev \
        autoconf \
        automake \
        libtool \
        cmake  \
        fonts-liberation \
        google-perftools \
        # C++
        libtbb-dev \
        qt5-default \
        libgflags-dev \
        libeigen3-dev \
        # Fortran
        gfortran \
        # Go
        libgoogle-glog-dev \
        # Math libs
        libatlas-base-dev \
        # Data libs
        libhdf5-dev \
        # Doc libs
        doxygen \
        # Compression libs
        gzip \
        lzop \
        libarchive-tools \
        zlibc \
        p7zip-full \
        unp \
        libbz2-dev \
        liblzma-dev \
        zlib1g-dev \
        libonig-dev \
        libzip-dev \
    # Cleanup
    && clean-layer.sh \
    # Fix permissions
    && fix-permissions.sh $HOME

### Install node.js
RUN \
    echo "**** installing node.js dev environment ****" \
    apt-get update \
    # https://nodejs.org/en/about/releases/ use even numbered releases, i.e. LTS versions
    #&& curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - \
    && curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash - \
    && apt-get install -y nodejs \
    # As conda is first in path, the commands 'node' and 'npm' reference to the version of conda.
    # Replace those versions with the newly installed versions of node
    #&& rm -f /opt/conda/bin/node && ln -s /usr/bin/node /opt/conda/bin/node \
    #&& rm -f /opt/conda/bin/npm && ln -s /usr/bin/npm /opt/conda/bin/npm \
    # Fix permissions
    && chmod a+rwx /usr/bin/node \
    && chmod a+rwx /usr/bin/npm \
    # Fix node versions - put into own dir and before conda:
    && mkdir -p /opt/node/bin \
    && ln -s /usr/bin/node /opt/node/bin/node \
    && ln -s /usr/bin/npm /opt/node/bin/npm \
    # Install YARN
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends yarn \
    # Install typescript
    && /usr/bin/npm install -g typescript \
    # Install webpack - 32 MB
    && /usr/bin/npm install -g webpack \
    # Install node-gyp
    && /usr/bin/npm install -g node-gyp
    # Cleanup
    #clean-layer.sh # throws error

ENV PATH="/opt/node/bin:$PATH"

### Install NVM
RUN \
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 

### Install Java Runtime
RUN \
    echo "**** installing java dev environment ****" \
    apt-get update \
    && apt-get install -y --no-install-recommends openjdk-11-jdk maven scala \
    # Cleanup
    && clean-layer.sh

ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

### Install Golang dev environment
RUN \
    echo "**** installing golang dev environment ****" \
    && mkdir $RESOURCES_PATH"/golang" \
    && cd $RESOURCES_PATH"/golang" \
    && GO_VERSION=$(curl -sX GET https://go.dev/dl/ | grep -o '<span.*>.*linux-amd64.*</span>' | grep -oP '(?<=go).*(?=.linux)') \
    && wget --quiet https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz -O ~/go.tgz \
    && tar -C /usr/local -xzf ~/go.tgz \
    && rm ~/go.tgz \
    && echo "export PATH="/usr/local/go/bin:$PATH"" >> ~/.bashrc \
    # Cleanup
    && clean-layer.sh

RUN \
    rm -r $RESOURCES_PATH"/golang" \
    # Fix permissions \
    && fix-permissions.sh $HOME \
    # Cleanup
    && clean-layer.sh

ENV GOPATH="/go"
ENV PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

### Build and install Openresty
RUN \
    echo "**** installing Openresty web server ****" \
    && OPEN_RESTY_VERSION="1.19.9.1" \
    && mkdir $RESOURCES_PATH"/openresty" \
    && cd $RESOURCES_PATH"/openresty" \
    && apt-get update \
    && apt-get purge -y \
        nginx \
        nginx-common \
    # libpcre required, otherwise you get a 'the HTTP rewrite module requires the PCRE library' error
    # Install apache2-utils to generate user:password file for nginx.
    && apt-get install -y \
        libssl-dev \
        libpcre3 \
        libpcre3-dev \
        apache2-utils \
    && wget --no-verbose https://openresty.org/download/openresty-$OPEN_RESTY_VERSION.tar.gz  -O ./openresty.tar.gz \
    && tar xfz ./openresty.tar.gz \
    && rm ./openresty.tar.gz \
    && cd ./openresty-$OPEN_RESTY_VERSION/ \
    # Surpress output - if there is a problem remove  > /dev/null
    && ./configure --with-http_stub_status_module --with-http_sub_module > /dev/null \
    && make -j2 > /dev/null \
    && make install > /dev/null \
    # create log dir and file - otherwise openresty will throw an error
    && mkdir -p /var/log/nginx/ \
    && touch /var/log/nginx/upstream.log \
    && cd $RESOURCES_PATH \
    && rm -r $RESOURCES_PATH"/openresty" \
    # Cleanup
    && clean-layer.sh \
    # Fix permissions
    && fix-permissions.sh $HOME

ENV PATH="/usr/local/openresty/nginx/sbin:$PATH"

### Build and install Caddy with additional plugins
RUN \
    echo "**** installing xcaddy builder ****" \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        libnss3-tools \
    && go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest \
    # Cleanup
    && clean-layer.sh

RUN \
    echo "**** building caddy ****" \
    && CGO_ENABLED=0 GOARCH=amd64 GOOS=linux \
        xcaddy build \
        --with github.com/caddy-dns/gandi \
        --with github.com/caddy-dns/cloudflare \
        --with github.com/caddy-dns/dnspod \
        --with github.com/caddy-dns/duckdns \
        --with github.com/greenpau/caddy-security \
        --with github.com/greenpau/caddy-trace \
        --output $RESOURCES_PATH"/caddy" \
    && cp $RESOURCES_PATH"/caddy" /usr/bin/caddy \
    && rm -r $RESOURCES_PATH"/caddy" \
    # Cleanup
    && clean-layer.sh \
    && fix-permissions.sh $HOME

### Install SSH
RUN \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        openssh-client \
        openssh-server \
        # SSLH for SSH + HTTP(s) Multiplexing
        sslh \
        # SSH Tooling
        autossh \
        mussh && \
    chmod go-w $HOME \
    && mkdir -p $HOME/.ssh/ \
    # create empty config file if not exists
    touch $HOME/.ssh/config \
    && chown -R $NB_USER:users $HOME/.ssh \
    && chmod 700 $HOME/.ssh \
    && printenv >> $HOME/.ssh/environment \
    && chmod -R a+rwx /usr/local/bin/ \
    # Cleanup
    && clean-layer.sh \
    # Fix permissions
    && fix-permissions.sh $HOME


### Install pyenv to allow dynamic creation of python versions
RUN git clone https://github.com/pyenv/pyenv.git $RESOURCES_PATH/.pyenv

### Install pyenv plugins based on pyenv installer
RUN git clone https://github.com/pyenv/pyenv-virtualenv.git $RESOURCES_PATH/.pyenv/plugins/pyenv-virtualenv
RUN git clone https://github.com/pyenv/pyenv-doctor.git $RESOURCES_PATH/plugins/pyenv-doctor
RUN git clone https://github.com/pyenv/pyenv-update.git $RESOURCES_PATH/plugins/pyenv-update
RUN git clone https://github.com/pyenv/pyenv-which-ext.git $RESOURCES_PATH/plugins/pyenv-which-ext

### Add pyenv to path
ENV \
    PATH="$RESOURCES_PATH/.pyenv/shims:$RESOURCES_PATH/.pyenv/bin:$PATH" \
    PYENV_ROOT="$RESOURCES_PATH/.pyenv"

### Install pip packages and setup pipx
ENV \
    PIPX_HOME="/usr/local/pipx" \
    PIPX_BIN_DIR="/usr/local/pipx/bin" \
    PATH="/usr/local/pipx/bin:$PATH"
RUN \
    mkdir -p "$PIPX_HOME" "$PIPX_BIN_DIR" && chmod -R 777 "$PIPX_HOME" \
    && pip3 install \
        pipx \
        pip-api \
        wheel \
        ipython \
        psutil \
        python-crontab \
        pyyaml \
        yamale \
        typing \
        docker \
        ansible \
        passlib \
        bcrypt \
        watchgod \
        coloredlogs \
    # Cleanup
    && clean-layer.sh

### Install pipx packages
RUN \
    pipx install \
        httpie --force \
    # Cleanup
    && clean-layer.sh

### Install databases
# Install Mongo
RUN \
    wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add - \
    && echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update && apt-get install -y --no-install-recommends \
        mongodb-org
# Install Postgres
RUN \
    apt-get update && apt-get install -y --no-install-recommends \
        postgresql postgresql-contrib


### Install latest supervisor for process supervision
RUN \
    apt-get update \
    && apt-get install -y --no-install-recommends rsyslog \
    # Create sshd run directory - required for starting process via supervisor
    && mkdir -p /var/run/sshd && chmod 400 /var/run/sshd \
    # Install rsyslog for syslog logging
    && pipx install --force supervisor \
    && pipx inject supervisor supervisor-stdout \
    # supervisor needs this logging path
    && mkdir -p /var/log/supervisor/ \
    # Cleanup
    && clean-layer.sh

### Update paths allowed by sudo
RUN \
    echo "Defaults secure_path=$PATH" > /etc/sudoers.d/securepath \
    && chmod 0440 /etc/sudoers.d/securepath

WORKDIR /root
