FROM registry.dev.proneer.co/core-gpu:dev.conda

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    docker.io \
    && fix-permissions.sh $HOME \
    # Cleanup
    && clean-layer.sh \
	&& rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y apt-transport-https
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

# change to kubernetes-focal when it becomes available
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update && apt-get install -y \
    kubectl \
    # Fix permissions
    && fix-permissions.sh $HOME \
    # Cleanup
    && clean-layer.sh

# RUN apt-get install --reinstall systemd -y
WORKDIR /root